sudo: false
language: node_js
node_js:
  - "5.3"
cache:
  directories:
    - node_modules
    - bower_components
install:
  - travis_retry npm install -g bower polylint web-component-tester
  - travis_retry npm install
  - travis_retry bower install
script:
  - npm run lint
  - travis_retry npm test
